config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
        sessions: "admin/sessions",
      }
  devise_for :stores, skip: [:passwords], controllers: {
      registrations: "store/registrations",
      sessions: "store/sessions"
    }
  devise_for :customers, skip: [:passwords], controllers: {
      registrations: "public/registrations",
      sessions: "public/sessions"
    }
  # guest login
  devise_scope :customer do
    post "customers/guest_sign_in", to: "public/sessions#guest_sign_in"
  end
  # 店舗側
  namespace :store do
    resources :stores do
      resources :items
    end
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
    resources :customers, only: [:index, :show, :edit, :update]
    get "search" => "searches#search"
  end
  # 管理者側
  namespace :admin do
    resources :stores, only: [:index, :show, :create]
    get '/', to: 'admin/home#top'
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    get "search" => "searches#search"
  end
  # 顧客側
  scope module: :public do
    resources :stores, only: [:index] do
      resource :favorite, only: [:create, :destroy]
      resources :items, only: [:index, :show]
    end
    resources :customers, only: [:update] do
      member do
        get :favorites
      end
    end
      get '/customers/withdraw_confirm' => 'customers#withdraw_confirm', as: "withdraw_confirm"
      patch '/customers/withdraw' => 'customers#withdraw'
      get '/customers/mypage' => 'customers#show', as: "mypage"
      get '/customers/confirmation' => 'customers#confirmation', as: 'confirmation'
      get 'customers/infomation/edit' => 'customers#edit', as: "infomation"
    resources :cart_items, except: [:show, :edit, :new]
      delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    get 'orders/thanks' => 'orders#thanks'
    post 'orders/confirm' => 'orders#confirm', as: "confirm"
    get 'orders/possible' => 'orders#possible', as: "possible"
    get 'orders/production' => 'orders#production', as: "prodction"
    get 'orders/review' => 'orders#review', as: "review"
    resources :orders, except: [:edit, :update, :destroy]
    root to: 'homes#top'
    get "search" => "searches#search"
  end
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  belongs_to :store
  has_one_attached :image
  
  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/logo.PNG')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end
  
  def with_tax_price
    (price * 1.1).floor
  end
  
  with_options presence: true do
    validates :name
    validates :price
    validates :store_id
  end
end

app/models/store.rb
class Store < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :items, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_one_attached :image
   
  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/logo.PNG')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end
  
  def favorited_by?(current_customer)
    favorites.exists?(customer_id: current_customer.id)
  end
  
  def self.ransackable_attributes(auth_object = nil)
    ["address", "created_at", "email", "encrypted_password", "id", "introduction", "name", "remember_created_at", "reset_password_sent_at", "reset_password_token", "telephone_number", "updated_at"]
  end
  
  with_options presence: true do
    validates :name
    validates :address
    validates :telephone_number
  end
end

app/controllers/admin/stores_controller.rb
class Admin::StoresController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @stores = Store.page(params[:page])
  end
  
  def show
    @store = Store.find(params[:id])
  end
  
  private
  
  def store_params
    params.require(:store).permit(:email, :encrypted_password, :name, :address, :telephone_number)
  end
end

app/controllers/store/confirmations_controller.rb
# frozen_string_literal: true

class Store::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/store/customers_controller.rb
class Store::CustomersController < ApplicationController
end

app/controllers/store/favorites_controller.rb
class Store::FavoritesController < ApplicationController
  
  def create
    store = Store.find(params[:store_id])
    favorite = current_customer.favorite.new(store_id: store.id)
    favorite.save
    redirect_to request.referer
  end
  
  def destroy
    store = Store.find(params[:store_id])
    favorite = current_customer.favorite.find_by(store_id: store.id)
    favorite.destroy
    redirect_to request.referer
  end
end

app/controllers/store/items_controller.rb
class Store::ItemsController < ApplicationController
  before_action :authenticate_store!
  before_action :set_item, only: [:show, :edit, :update]
  
  def index
    @store = current_store
    @items = @store.items
  end
  
  def new
    @item = Item.new
  end
  
  def create
    @item = Item.new(item_params)
    @item.store_id = current_store.id
    if @item.save
      flash[:notice] = "メニューを追加しました。"
      redirect_to store_store_items_path
    else
      render :new
    end
  end
  
  def show
    @store = current_store
  end
  
  def edit
    @store = current_store
  end
  
  def update
    if @item.update(item_params)
      flash[:notice] = "メニューを編集しました。"
      redirect_to store_store_items_path
    else
      render :edit
    end
  end
  
  private
  
  def item_params
    params.require(:item).permit(:name, :introduction, :price, :is_active, :image)
  end
  
  def set_item
    @item = Item.find(params[:id])
  end
end

app/controllers/store/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Store::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/store/order_details_controller.rb
class Store::OrderDetailsController < ApplicationController
end

app/controllers/store/orders_controller.rb
class Store::OrdersController < ApplicationController
end

app/controllers/store/passwords_controller.rb
# frozen_string_literal: true

class Store::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/store/registrations_controller.rb
# frozen_string_literal: true

class Store::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/store/searches_controller.rb
class Store::SearchesController < ApplicationController
end

app/controllers/store/sessions_controller.rb
# frozen_string_literal: true

class Store::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  
  def after_sign_in_path_for(resource)
    store_store_items_path(current_store)
  end
  
  def after_sign_out_path_for(resource)
    new_store_session_path
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/store/stores_controller.rb
class Store::StoresController < ApplicationController
  before_action :authenticate_store!
  before_action :set_store, only: [:show, :edit, :update]
  
  def show
  end
  
  def edit
  end
  
  def update
    if @store.update(store_params)
      redirect_to store_store_path(@store)
    else
      render :edit
    end
  end
  private
  
  def store_params
    params.require(:store).permit(:email, :password, :telephone_number, :image, :name, :address)
  end
  
  def set_store
    @store = Store.find(params[:id])
  end
end

app/controllers/store/unlocks_controller.rb
# frozen_string_literal: true

class Store::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/stores_helper.rb
module Admin::StoresHelper
end

app/helpers/store/customers_helper.rb
module Store::CustomersHelper
end

app/helpers/store/favorites_helper.rb
module Store::FavoritesHelper
end

app/helpers/store/items_helper.rb
module Store::ItemsHelper
end

app/views/store/items/edit.html.erb
<div class="container">
  <div class="row">
    <div class="offset-5 mb-5">
      <h6><strong>商品編集</strong> <%= @store.name %></h6>
    </div>
    <div class="offset-3 col-lg-8">
      <%= form_with model: @item, url: store_store_item_path do |f| %>
      <table class="table table-borderless">
        <tbody>
          <tr>
            <td>商品画像</td>
            <td><%= f.file_field :image, accept: "image/*" %></td>
          </tr>
          <tr>
            <td>商品名</td>
            <td><%= f.text_field :name, :placeholder => "商品名" %></td>
          </tr>
          <tr>
            <td>商品説明</td>
            <td><%= f.text_area :introduction, :placeholder => "説明文を追加してください。" %></td>
          </tr>
          <tr>
            <td>税抜価格</td>
            <td>¥ <%= f.number_field :price, :placeholder => "1000" %></td>
          </tr>
          <tr>
            <td>販売ステータス</td>
            <td>
              <%= f.radio_button :is_active, :true %>
              <%= f.label :is_active, "販売中", class: 'text-black-50 mr-3' %>
              <%= f.radio_button :is_active, :false %>
              <%= f.label :is_active, "販売停止中", class: 'text-black-50' %>
            </td>
          </tr>
        </tbody>
      </table>
      <div class="col-lg-2 offset-2 mt-3">
        <%= f.submit "変更を保存", class: 'btn btn-success pr-5 pl-5' %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/store/items/index.html.erb
<div class="container">
  <div class="row">
    <div class="col mb-5">
      <h4><strong><%= @store.name %></strong> 商品一覧</h4>
    </div>
    <div class="justify-content-end">
      <%= link_to new_store_store_item_path do %>
        <button type="button" class="btn btn-dark rounded-circle p-0" style="width:2rem;height:2rem;">+</button>
      <% end %>
    </div>
  </div>
  <div class="row mb-5">
    <% @items.each do |item| %>
      <div class="col-lg-2">
        <%= link_to store_store_item_path(@store, item) do %>
          <%= image_tag item.get_image(150, 120), class: 'item-img' %>
        <% end %>
      </div>
      <div class="col-lg-2">
        <p><strong><%= item.name %></strong></p>
        <p><%= item.introduction %></p>
        <p>¥<%= item.price %></p>
        <p>
          <% if item.is_active %>
            <span class="text-success"><strong>販売中</strong></span>
          <% else %>
            <span class="text-danger"><strong>販売停止中</strong></span>
          <% end %>
        </p>
      </div>
    <% end %>
  </div>
</div>

app/views/store/items/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 mb-3">
      <h4 class="text-center">商品新規登録</h4>
    </div>
    <div class="col-md-6 offset-3">
    <%= form_with model: [@store, @item], url: store_store_items_path do |f| %>
      <table class="table table-borderless">
        <tbody>
          <tr>
            <td>商品画像</td>
            <td><%= f.file_field :image, accept: "image/*" %></td>
          </tr>
          <tr>
            <td>商品名</td>
            <td><%= f.text_field :name, :placeholder => "商品名" %></td>
          </tr>
          <tr>
            <td>商品説明</td>
            <td><%= f.text_area :introduction, :placeholder => "ここに説明文を記述します", size: "40×60" %></td>
          </tr>
          <tr>
            <td>税抜価格</td>
            <td><%= f.number_field :price, :placeholder => "1000", size: 40 %>円</td>
          </tr>
          <tr>
            <td>販売ステータス</td>
            <td>
              <%= f.radio_button :is_active, :true %>
              <%= f.label :is_active, "販売中", class: 'text-black-50 mr-3' %>
              <%= f.radio_button :is_active, :false %>
              <%= f.label :is_active, "販売停止中", class: 'text-black-50' %>
            </td>
          </tr>
        </tbody>
      </table>
      <hr class="hr">
    </div>
    <div class="col-lg-4 offset-4">
      <%= f.submit "新規登録", class: "btn btn-success btn-block mt-4" %>
    </div>
    <% end %>
    </div>
  </div>
</div>

app/views/store/items/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12 mb-5">
      <h6 class="text-center"><strong>商品詳細</strong> <%= @store.name %></h6>
    </div>
  </div>
  <div class="row mt-5">
    <div class="col-lg-4 offset-2">
      <%= image_tag @item.get_image(300, 300) %>
    </div>
    <div class="col-lg-6">
      <h4><strong><%= @item.name %></strong></h4>
      <p><%= @item.introduction %></p>
      <h6>
         ¥ <%= @item.with_tax_price %>
        <span style="font-size:10px;">(税込)</span>
      </h6>
      <h6>
        <% if @item.is_active %>
          <span class="text-success"><strong>販売中</strong></span>
        <% else %>
          <span class="text-danger"><strong>販売停止中</strong></span>
        <% end %>
      </h6>
      <span><%= link_to "編集する", edit_store_store_item_path(@item.id), class: 'btn btn-success pr-5 pl-5 mt-4' %></span>
    </div>
  </div>
</div>