config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
        sessions: "admin/sessions",
      }
  devise_for :stores, skip: [:passwords], controllers: {
      registrations: "store/registrations",
      sessions: "store/sessions"
    }
  devise_for :customers, skip: [:passwords], controllers: {
      registrations: "public/registrations",
      sessions: "public/sessions"
    }
  # guest login
  devise_scope :customer do
    post "customers/guest_sign_in", to: "public/sessions#guest_sign_in"
  end
  # 店舗側
  namespace :store do
    resources :stores do
      resources :items
    end
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
    resources :customers, only: [:index, :show, :edit, :update]
    get "search" => "searches#search"
  end
  # 管理者側
  namespace :admin do
    resources :stores, only: [:index, :show, :create]
    get '/', to: 'admin/home#top'
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    get "search" => "searches#search"
  end
  # 顧客側
  scope module: :public do
    resources :stores, only: [:index] do
      resource :favorite, only: [:create, :destroy]
      resources :items, only: [:index, :show]
    end
    resources :customers, only: [:update] do
      member do
        get :favorites
      end
    end
      get '/customers/withdraw_confirm' => 'customers#withdraw_confirm', as: "withdraw_confirm"
      patch '/customers/withdraw' => 'customers#withdraw'
      get '/customers/mypage' => 'customers#show', as: "mypage"
      get '/customers/confirmation' => 'customers#confirmation', as: 'confirmation'
      get 'customers/infomation/edit' => 'customers#edit', as: "infomation"
    resources :cart_items, except: [:show, :edit, :new]
      delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    get 'orders/thanks' => 'orders#thanks'
    post 'orders/confirm' => 'orders#confirm', as: "confirm"
    get 'orders/possible' => 'orders#possible', as: "possible"
    get 'orders/production' => 'orders#production', as: "prodction"
    get 'orders/review' => 'orders#review', as: "review"
    resources :orders, except: [:edit, :update, :destroy]
    root to: 'homes#top'
    get "search" => "searches#search"
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_one_attached :profile_image
  
  enum gender: { male: 0, female: 1, no_answer: 2 }
  
  def active_for_authentication?
    super && (is_active == true ) # 有効でないとログインできない
  end
  
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/logo.PNG')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
  
  def full_name
    last_name + first_name
  end
  
  def full_name_kana
    last_name_kana + first_name_kana
  end
  
  def self.guest
    find_or_create_by!(email: 'guest@email.com') do |customer|
      customer.password = SecureRandom.urlsafe_base64
      customer.last_name = "ゲスト"
      customer.first_name = "太郎"
      customer.last_name_kana = "ゲスト"
      customer.first_name_kana = "タロウ"
      customer.telephone_number = "00000000000"
      customer.gender = "no_answer"
      customer.is_active = true
    end
  end
  
  with_options presence: true do
    validates :last_name, format: { with: /\A[一-龥]+\z/ }
    validates :first_name, format: { with: /\A[一-龥]+\z/ }
    validates :kast_name_kana, format: { with: /\A[ァ-ヶー－]+\z/ }
    validates :first_name_kana, format: { with: /\A[ァ-ヶー－]+\z/ }
    validates :telephone_number, format: { with: /\A\d{10,11}\z/ }
    validates :gender
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @customers = Customer.page(params[:page])
  end
  
  def show
    @customer = Customer.find(params[:id])
  end
  
  private
  
  def customer_params
    params.require(:customer).permit(:email, :encrypted_password, :last_name, :first_name, :last_name_kana, :first_name_kana, :telephone_number, :gender, :is_active)
  end
end

app/controllers/store/customers_controller.rb
class Store::CustomersController < ApplicationController
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/store/customers_helper.rb
module Store::CustomersHelper
end

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-2 offset-5 mb-5">
      <h4><strong>会員一覧</strong></h4>
    </div>
    <div class="offset-2 col-lg-8">
      <table class="table table-hover">
        <thead class="thead-light">
          <tr>
            <td>会員ID</td>
            <td>氏名</td>
            <td>メールアドレス</td>
            <td>ステータス</td>
          </tr>
        </thead>
        <tbody>
          <% @customers.each do |customer| %>
          <tr>
            <td><%= customer.id %></td>
            <td>
              <%= link_to admin_customer_path(customer.id), class: 'text-dark' do %>
                <%= customer.last_name %><%= customer.first_name %>
              <% end %>
            </td>
            <td><%= customer.email %></td>
            <td>
              <% if customer.is_active == true %>
                <p class="text-success"><strong><%= "有効" %></strong></p>
              <% else %>
                <p class="text-danger"><strong><%= "退会" %></strong></p>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<%= paginate @customers %>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12 text-center">
      <h4><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</h4>
    </div>
    <div class="col-md-6 offset-3 mt-5">
      <table class="table table-borderless" bgcolor="#e6e6e6">
        <tbody>
          <tr>
            <td>会員ID</td>
            <td><%= @customer.id %></td>
          </tr>
          <tr>
            <td>氏名</td>
            <td><%= @customer.last_name %> <%= @customer.first_name %></td>
          </tr>
          <tr>
            <td>フリガナ</td>
            <td><%= @customer.last_name_kana %> <%= @customer.first_name_kana %></td>
          </tr>
          <tr>
            <td>電話番号</td>
            <td><%= @customer.telephone_number %></td>
          </tr>
          <tr>
            <td>メールアドレス</td>
            <td><%= @customer.email %></td>
          </tr>
          <tr>
            <td>会員ステータス</td>
            <td>
              <% if @customer.is_active == true %>
                <p class="text-success"><strong><%= "有効" %></strong></p>
              <% else %>
                <p class="text-danger"><strong><%= "退会" %></strong></p>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>