config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
        sessions: "admin/sessions",
      }
  devise_for :stores, skip: [:passwords], controllers: {
      registrations: "store/registrations",
      sessions: "store/sessions"
    }
  devise_for :customers, skip: [:passwords], controllers: {
      registrations: "public/registrations",
      sessions: "public/sessions"
    }
  # guest login
  devise_scope :customer do
    post "customers/guest_sign_in", to: "public/sessions#guest_sign_in"
  end
  # 店舗側
  namespace :store do
    resources :stores do
      resources :items
    end
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
    resources :customers, only: [:index, :show, :edit, :update]
    get "search" => "searches#search"
  end
  # 管理者側
  namespace :admin do
    resources :stores, only: [:index, :show, :create]
    get '/', to: 'admin/home#top'
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    get "search" => "searches#search"
  end
  # 顧客側
  scope module: :public do
    resources :stores, only: [:index] do
      resource :favorite, only: [:create, :destroy]
      resources :items, only: [:index, :show]
    end
    resources :customers, only: [:update] do
      member do
        get :favorites
      end
    end
      get '/customers/withdraw_confirm' => 'customers#withdraw_confirm', as: "withdraw_confirm"
      patch '/customers/withdraw' => 'customers#withdraw'
      get '/customers/mypage' => 'customers#show', as: "mypage"
      get '/customers/confirmation' => 'customers#confirmation', as: 'confirmation'
      get 'customers/infomation/edit' => 'customers#edit', as: "infomation"
    resources :cart_items, except: [:show, :edit, :new]
      delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    get 'orders/thanks' => 'orders#thanks'
    post 'orders/confirm' => 'orders#confirm', as: "confirm"
    get 'orders/possible' => 'orders#possible', as: "possible"
    get 'orders/production' => 'orders#production', as: "prodction"
    get 'orders/review' => 'orders#review', as: "review"
    resources :orders, except: [:edit, :update, :destroy]
    root to: 'homes#top'
    get "search" => "searches#search"
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details, dependent: :destroy
  belongs_to :customer
  has_many :reviews, dependent: :destroy
  
  enum payment_method: { credit_card: 0, cash: 1}
  
  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/logo.PNG')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end
  
  def subtotal
    payment_amount - fee
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @orders = Order.page(params[:page])
  end
  
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end
end

app/controllers/store/orders_controller.rb
class Store::OrdersController < ApplicationController
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/store/orders_helper.rb
module Store::OrdersHelper
end

app/views/admin/orders/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-3 mb-5">
      <h3>注文履歴一覧</h3>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-8 offset-2">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>購入日時</th>
            <th>購入者</th>
            <th>注文個数</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @orders.each do |order| %>
          <tr>
            <td><%= order.created_at.strftime('%Y/%m/%d %H:%M:%S') %></td>
            <td><%= order.customer.last_name %><%= order.customer.first_name %></td>
            <td><%= order.order_details.sum(:quantity) %></td>
            <td>
              <%= link_to "表示する", admin_order_path(order.id), class: 'btn btn-secondary rounded-pill pr-4 pl-4' %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <div class="row", style="text-align: center;">
        <div class="col-6 offset-5">
          <%= paginate @orders %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-3 mb-5">
      <h3>注文履歴詳細</h3>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-5">
      <table class="table border-bottom" bgcolor="#e6e6e6">
        <tbody class="bb1">
          <tr>
            <td>注文日</td>
            <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
          </tr>
          <tr>
            <td>購入者</td>
            <td><%= @order.customer.last_name %><%= @order.customer.first_name %></td>
          </tr>
          <tr>
            <td>支払方法</td>
            <td><%= @order.payment_method_i18n %></td>
          </tr>
          <tr>
            <td>商品合計</td>
            <td>¥<%= @order.subtotal %></td>
          </tr>
          <tr>
            <td>手数料</td>
            <td>¥<%= @order.fee %></td>
          </tr>
          <tr>
            <td>お支払い金額</td>
            <td>¥<%= @order.payment_amount %></td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="col-lg-6 offset-1">
      <table class="table border-top">
        <thead>
          <tr>
            <th>商品名</th>
            <th>単価(税込)</th>
            <th>数量</th>
            <th>小計</th>
          </tr>
        </thead>
        <tbody>
          <% @order.order_details.each do |order_detail| %>
          <tr>
            <td><%= order_detail.item.name %><br></td>
            <td>¥<%= order_detail.item.with_tax_price %></td>
            <td><%= order_detail.quantity %></td>
            <td>¥<%= order_detail.item.with_tax_price * order_detail.quantity %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>