config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
        sessions: "admin/sessions",
      }
  devise_for :stores, skip: [:passwords], controllers: {
      registrations: "store/registrations",
      sessions: "store/sessions"
    }
  devise_for :customers, skip: [:passwords], controllers: {
      registrations: "public/registrations",
      sessions: "public/sessions"
    }
  # guest login
  devise_scope :customer do
    post "customers/guest_sign_in", to: "public/sessions#guest_sign_in"
  end
  # 店舗側
  namespace :store do
    resources :stores do
      resources :items
    end
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
    resources :customers, only: [:index, :show, :edit, :update]
    get "search" => "searches#search"
  end
  # 管理者側
  namespace :admin do
    resources :stores, only: [:index, :show, :create]
    get '/', to: 'admin/home#top'
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    get "search" => "searches#search"
  end
  # 顧客側
  scope module: :public do
    resources :stores, only: [:index] do
      resource :favorite, only: [:create, :destroy]
      resources :items, only: [:index, :show]
    end
    resources :customers, only: [:update] do
      member do
        get :favorites
      end
    end
      get '/customers/withdraw_confirm' => 'customers#withdraw_confirm', as: "withdraw_confirm"
      patch '/customers/withdraw' => 'customers#withdraw'
      get '/customers/mypage' => 'customers#show', as: "mypage"
      get '/customers/confirmation' => 'customers#confirmation', as: 'confirmation'
      get 'customers/infomation/edit' => 'customers#edit', as: "infomation"
    resources :cart_items, except: [:show, :edit, :new]
      delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    get 'orders/thanks' => 'orders#thanks'
    post 'orders/confirm' => 'orders#confirm', as: "confirm"
    get 'orders/possible' => 'orders#possible', as: "possible"
    get 'orders/production' => 'orders#production', as: "prodction"
    get 'orders/review' => 'orders#review', as: "review"
    resources :orders, except: [:edit, :update, :destroy]
    root to: 'homes#top'
    get "search" => "searches#search"
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :item
    belongs_to :customer
    
    def subtotal
      item.with_tax_price * quantity
    end
    
    validates :quantity, presence: true #空でないこと
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_one_attached :profile_image
  
  enum gender: { male: 0, female: 1, no_answer: 2 }
  
  def active_for_authentication?
    super && (is_active == true ) # 有効でないとログインできない
  end
  
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/logo.PNG')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
  
  def full_name
    last_name + first_name
  end
  
  def full_name_kana
    last_name_kana + first_name_kana
  end
  
  def self.guest
    find_or_create_by!(email: 'guest@email.com') do |customer|
      customer.password = SecureRandom.urlsafe_base64
      customer.last_name = "ゲスト"
      customer.first_name = "太郎"
      customer.last_name_kana = "ゲスト"
      customer.first_name_kana = "タロウ"
      customer.telephone_number = "00000000000"
      customer.gender = "no_answer"
      customer.is_active = true
    end
  end
  
  with_options presence: true do
    validates :last_name, format: { with: /\A[一-龥]+\z/ }
    validates :first_name, format: { with: /\A[一-龥]+\z/ }
    validates :kast_name_kana, format: { with: /\A[ァ-ヶー－]+\z/ }
    validates :first_name_kana, format: { with: /\A[ァ-ヶー－]+\z/ }
    validates :telephone_number, format: { with: /\A\d{10,11}\z/ }
    validates :gender
  end
end

app/models/end_user.rb
class EndUser < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :customer
  belongs_to :store
  
  validates :customer_id, uniqueness: {scope: :store_id}
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  belongs_to :store
  has_one_attached :image
  
  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/logo.PNG')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end
  
  def with_tax_price
    (price * 1.1).floor
  end
  
  with_options presence: true do
    validates :name
    validates :price
    validates :store_id
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details, dependent: :destroy
  belongs_to :customer
  has_many :reviews, dependent: :destroy
  
  enum payment_method: { credit_card: 0, cash: 1}
  
  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/logo.PNG')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end
  
  def subtotal
    payment_amount - fee
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :item
    belongs_to :order
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :customer
  belongs_to :order
end

app/models/store.rb
class Store < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :items, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_one_attached :image
   
  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/logo.PNG')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end
  
  def favorited_by?(current_customer)
    favorites.exists?(customer_id: current_customer.id)
  end
  
  def self.ransackable_attributes(auth_object = nil)
    ["address", "created_at", "email", "encrypted_password", "id", "introduction", "name", "remember_created_at", "reset_password_sent_at", "reset_password_token", "telephone_number", "updated_at"]
  end
  
  with_options presence: true do
    validates :name
    validates :address
    validates :telephone_number
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :search
  
  def search
    @q = Store.ransack(params[:q])
    @store = @q.result(distinct: true).page(params[:page])
    @result = params[:q]&.values&.reject(&:blank?)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :telephone_number, :gender, :birth_date, :name, :address])
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/helpers/admin/stores_helper.rb
module Admin::StoresHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/store/items_helper.rb
module Store::ItemsHelper
end

app/helpers/store/orders_helper.rb
module Store::OrdersHelper
end

app/helpers/store/stores_helper.rb
module Store::StoresHelper
end

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_header_admin.html.erb
<li class="nav-item">
  <%= link_to "店舗一覧", admin_stores_path, class: "nav-link text-dark" %>
</li>
<li class="nav-item">
  <%= link_to "会員一覧", admin_customers_path, class: 'nav-link text-dark' %>
</li>
<li class="nav-item">
  <%= link_to "注文履歴一覧", admin_orders_path, class: 'nav-link text-dark' %>
</li>
<li class="nav-item">
  <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "nav-link text-dark" %>
</li>

app/views/layouts/_header_before.erb
<li class="nav-item mr-3">
  <%= link_to "店舗一覧", stores_path, class: "nav-link text-dark mt-2" %>
</li>
<li class="nav-item">
  <%= link_to "ゲストログイン", customers_guest_sign_in_path, method: :post, class: 'nav-link text-dark mt-2' %>
</li>
<li class="nav-item mr-3">
  <%= link_to new_customer_registration_path, class: "btn btn-header btn-sm rounded-pill p-3" do %>
    <i class="fa-solid fa-user-plus"></i>
    <span class='header-btn-text'>新規登録</span>
  <% end %>
</li>
<li class="nav-item">
  <%= link_to new_customer_session_path, class: "btn btn-header btn-sm rounded-pill p-3" do %>
    <i class="fa-solid fa-arrow-right-to-bracket"></i>
    <span class='header-btn-text'>ログイン</span>
  <% end %>
</li>

app/views/layouts/_header_customer.html.erb
<li class="nav-item mr-3">
  <%= link_to "マイページ", mypage_path(current_customer), class: "nav-link text-dark" %>
</li>
<li class="nav-item mr-3">
  <%= link_to "店舗一覧", stores_path, class: "nav-link text-dark" %>
</li>
<li class="nav-item mr-3">
  <%= link_to "カート", cart_items_path, class: "nav-link text-dark" %>
</li>
<li class="nav-item">
  <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "nav-link text-dark" %>
</li>

app/views/layouts/_header_store.html.erb
<li class="nav-item">
  <%= link_to "商品一覧", store_store_items_path(current_store), class: 'nav-link text-dark' %>
</li>
<li class="nav-item">
  <%= link_to "店舗詳細", store_store_path(current_store), class: 'nav-link text-dark' %>
</li>
<li class="nav-item">
  <%= link_to "ログアウト", destroy_store_session_path, method: :delete, class: 'nav-link text-dark' %>
</li>

app/views/layouts/_search.html.erb
<% if controller_name != 'sessions' %>
<div class="search_form pe-3">
  <%= search_form_for @q, url: search_path, class: 'row justify-content-end' do |f| %>
  <div class="col-lg-8 p-0">
    <%= f.search_field :name_cont, class: 'form-control' %>
  </div>
  <div class="col-lg-1 p-0">
    <button class="btn btn-outline-success" type="submit">
      <i class="fa-solid fa-magnifying-glass"></i>
    </button>
  </div>
  <% end %>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OrderEats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1, maximum-scale=1">
    
    <script src="https://kit.fontawesome.com/81e1251ca7.js" crossorigin="anonymous"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header>
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand p-3" href="/"><%= image_tag('logo.PNG', size: "80x80") %></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if customer_signed_in? %>
                <%= render 'layouts/header_customer' %>
              <% elsif admin_signed_in? %>
                <%= render 'layouts/header_admin' %>
              <% elsif store_signed_in? %>
                <%= render 'layouts/header_store' %>
              <% else %>
                <%= render 'layouts/header_before' %>
              <% end %>
            </ul>
          </div>
          <div class="header_search">
            <%= render 'layouts/search' %>
          </div>
        </div>
      </nav>
    </header>
    <main>
      <% flash.each do |messege_type, messege| %>
        <div class="flash-message <%= messege_type %> alert alert-danger text-center col-md-4 offset-4"><%= messege %></div>
      <% end %>
      <%= yield %>
    </main>
    <footer class="footer mt-auto py-3">
      <div class="container">
        <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top footer mt-auto py-3 bg-body-tertiary">
          <div class="col-md-4 d-flex align-items-center">
            <a href="/" class="mb-3 me-2 mb-md-0 text-body-secondary text-decoration-none lh-1">
              <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"/></svg>
            </a>
            <span class="text-body-secondary">&copy; 2024 OrderEats</span>
          </div>
      
          <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
            <li class="ms-3"><a class="text-secondary" href="#"><svg class="bi" width="24" height="24"><i class="fa-brands fa-x-twitter"></i></svg></a></li>
            <li class="ms-3"><a class="text-secondary" href="#"><svg class="bi" width="24" height="24"><i class="fa-brands fa-square-instagram"></i></svg></a></li>
            <li class="ms-3"><a class="text-secondary" href="#"><svg class="bi" width="24" height="24"><i class="fa-brands fa-facebook"></i></svg></a></li>
          </ul>
        </footer>
      </div>
    </footer>
  </body>
</html>